// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.T25Piirivalve.entities;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PIIRIVALVUR_PIIRIPUNKTIS_Roo_Configurable {
    
    declare @type: PIIRIVALVUR_PIIRIPUNKTIS: @Configurable;
    
}
